# Simple Airflow setup
services:
  airflow:
    image: apache/airflow:2.7.1-python3.10
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/airflow.db
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
    volumes:
      - ./dags:/opt/airflow/dags
      - ./include:/opt/airflow/include
      - ./plugins:/opt/airflow/plugins
      - airflow-db:/opt/airflow
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install --quiet requests pandas soda-core-postgres apache-airflow-providers-postgres &&
               airflow db migrate &&
               airflow users create -u admin -p admin -f Admin -l User -r Admin -e admin@example.com 2>/dev/null || true &&
               airflow webserver &
               airflow scheduler"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  airflow-db:
