version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: olympics_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: olympics_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  streamlit:
    image: python:3.11-slim
    container_name: olympics_app
    working_dir: /app
    depends_on:
      - postgres
    ports:
      - "8517:8517"
    volumes:
      - ./app:/app
    command: >
      bash -c "pip install -q streamlit psycopg2-binary pandas &&
               streamlit run app.py --server.port 8517 --server.address 0.0.0.0"

